name       : libkdcraw
version    : 18.08.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/libkdcraw-18.08.2.tar.xz : f752be30e3c7b2326d4ae3d4bb44237ea9a873232a66d1be8102212f3485dcef
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.library
optimize   : lto
summary    : C++ interface to LibRaw
description: |
    Libkdcraw is a C++ interface around LibRaw library used to decode RAW picture files.
builddeps  :
    - pkgconfig(libraw)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
