name       : libkdcraw
version    : 19.08.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/libkdcraw-19.08.2.tar.xz : 735ab40633efec394c6265d83f86ad7caf278f63d1dd33cc6edf572da4925fcb
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
optimize   : lto
summary    : C++ interface to LibRaw
description: |
    Libkdcraw is a C++ interface around LibRaw library used to decode RAW picture files.
builddeps  :
    - pkgconfig(libraw)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
