name       : libkdcraw
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libkdcraw-17.12.1.tar.xz : b2afdd51b85e871e08e36639bd51fd86f689126fe7ee587fdeace9728f0e5116
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.library
optimize   : lto
summary    : C++ interface to LibRaw
description: |
    Libkdcraw is a C++ interface around LibRaw library used to decode RAW picture files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
