name       : libkdcraw
version    : 17.12.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/libkdcraw-17.12.0.tar.xz : 2771f2b23ad54ca04d7ca4ef76423a1157c7d35b9ae9d31b2a364e41e2e60ff1
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.library
optimize   : lto
summary    : C++ interface to LibRaw
description: |
    Libkdcraw is a C++ interface around LibRaw library used to decode RAW picture files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
