name       : libkdcraw
version    : 17.12.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/libkdcraw-17.12.2.tar.xz : c2d86fd2692ad84b565f097d13b0c6f0e6ed1cfe6ba56006a362899288f7dfe1
license    :
    - GPL-2.0
    - LGPL-2.1
component  : multimedia.library
optimize   : lto
summary    : C++ interface to LibRaw
description: |
    Libkdcraw is a C++ interface around LibRaw library used to decode RAW picture files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libraw)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
